-- KC Earn fresh production bootstrap
-- Target: iqdxbavymmijaybqsasw
-- Fresh public schema only; existing auth.users is preserved.
-- Review before execution. This file is never executed by the application.

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN CREATE TYPE public.video_category AS ENUM ('Funny','Music','Experience','Sports','Learning','Serious Topics'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.video_status AS ENUM ('processing','published','removed','failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.earning_source AS ENUM ('views','engagement','bonus','referral'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.app_role AS ENUM ('admin','moderator','user'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.reward_kind AS ENUM ('daily_login','referral','milestone','trending','challenge','event','promo'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.notification_kind AS ENUM ('earning_credited','withdrawal_requested','withdrawal_approved','withdrawal_rejected','campaign_approved','campaign_completed','reward_received','milestone_achieved','system'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.campaign_status AS ENUM ('draft','pending_review','active','paused','completed','rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.ad_event_type AS ENUM ('impression','click'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.withdrawal_status AS ENUM ('pending','processing','paid','rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, username text UNIQUE,
  display_name text NOT NULL DEFAULT 'New creator', bio text, location text, avatar_url text,
  referral_code text UNIQUE, email_normalized text, registration_phone text,
  country_code text NOT NULL DEFAULT 'NG', country_name text NOT NULL DEFAULT 'Nigeria',
  preferred_currency text NOT NULL DEFAULT 'NGN', locale text NOT NULL DEFAULT 'en-NG',
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.videos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL, description text, category public.video_category NOT NULL, video_path text NOT NULL,
  thumbnail_path text, duration_seconds integer, status public.video_status NOT NULL DEFAULT 'processing',
  views_count integer NOT NULL DEFAULT 0, likes_count bigint NOT NULL DEFAULT 0, comments_count bigint NOT NULL DEFAULT 0,
  source_provider text NOT NULL DEFAULT 'upload', source_url text, source_authorized_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.wallets (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE, available_balance numeric(14,2) NOT NULL DEFAULT 0,
  pending_balance numeric(14,2) NOT NULL DEFAULT 0, lifetime_earned numeric(14,2) NOT NULL DEFAULT 0,
  promotional_bonus_balance numeric(14,2) NOT NULL DEFAULT 0, referral_bonus_locked numeric(14,2) NOT NULL DEFAULT 0,
  referral_bonus_unlocked numeric(14,2) NOT NULL DEFAULT 0, real_earnings_balance numeric(14,2) NOT NULL DEFAULT 0,
  withdrawal_reserved_balance numeric(14,2) NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'NGN',
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.earnings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  video_id uuid REFERENCES public.videos(id) ON DELETE SET NULL, amount numeric(14,2) NOT NULL,
  source public.earning_source NOT NULL DEFAULT 'views', note text, external_reference text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.withdrawals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount numeric(14,2) NOT NULL CHECK (amount > 0), method text NOT NULL, destination text NOT NULL,
  status public.withdrawal_status NOT NULL DEFAULT 'pending', note text, platform_fee numeric(14,2) NOT NULL DEFAULT 0,
  payout_amount numeric(14,2), idempotency_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role public.app_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, role));
CREATE TABLE public.payout_config (id boolean PRIMARY KEY DEFAULT true CHECK (id), rate_per_view numeric NOT NULL DEFAULT 0.001, min_watch_seconds integer NOT NULL DEFAULT 5, min_watch_percent numeric NOT NULL DEFAULT 25, dedup_window_minutes integer NOT NULL DEFAULT 720, daily_creator_limit numeric NOT NULL DEFAULT 25, per_viewer_daily_limit numeric NOT NULL DEFAULT 0.25, daily_login_reward numeric NOT NULL DEFAULT 0.02, referral_reward numeric NOT NULL DEFAULT 0.50, milestone_reward numeric NOT NULL DEFAULT 1.00, min_withdrawal numeric NOT NULL DEFAULT 5, currency text NOT NULL DEFAULT 'NGN', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.video_views (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), video_id uuid NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE, creator_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, viewer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, session_key text, watch_seconds integer NOT NULL DEFAULT 0, percent_watched numeric NOT NULL DEFAULT 0, device text, ip_hash text, country text, is_valid boolean NOT NULL DEFAULT false, fraud_reason text, earned_amount numeric NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.reward_claims (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, kind public.reward_kind NOT NULL, reference text NOT NULL, amount numeric NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, kind, reference));
CREATE TABLE public.video_likes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), video_id uuid NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(video_id,user_id));
CREATE TABLE public.follows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), follower_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, following_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(follower_id,following_id));
CREATE TABLE public.video_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), video_id uuid NOT NULL REFERENCES public.videos(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, body text NOT NULL, parent_id uuid REFERENCES public.video_comments(id) ON DELETE CASCADE, edited_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, kind public.notification_kind NOT NULL DEFAULT 'system', title text NOT NULL, body text, metadata jsonb NOT NULL DEFAULT '{}', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.bank_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), creator_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, provider text NOT NULL, external_id text NOT NULL, bank_name text, account_name text, account_number_last4 text, verified boolean NOT NULL DEFAULT false, verified_at timestamptz, verification_reference text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(creator_id,provider,external_id));
CREATE TABLE public.account_verifications (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, phone_number text, phone_verified_at timestamptz, email_verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.verification_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, channel text NOT NULL CHECK(channel IN ('phone','email')), target text NOT NULL, code_hash text NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz, attempts integer NOT NULL DEFAULT 0 CHECK(attempts >= 0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.verification_bonus_claims (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, amount numeric(14,2) NOT NULL CHECK(amount > 0), currency text NOT NULL, status text NOT NULL CHECK(status IN ('PENDING_VERIFICATION_BONUS','CREDITED','EXPIRED')), expires_at timestamptz NOT NULL, credited_at timestamptz, expired_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id));
CREATE TABLE public.supported_countries (country_code text PRIMARY KEY, country_name text NOT NULL, currency text NOT NULL, locale text NOT NULL, is_live boolean NOT NULL DEFAULT false);
CREATE TABLE public.platform_reward_config (id boolean PRIMARY KEY DEFAULT true CHECK(id), country_code text NOT NULL DEFAULT 'NG', signup_bonus numeric(14,2) NOT NULL DEFAULT 3000, referral_target integer NOT NULL DEFAULT 10 CHECK(referral_target > 0), referral_reward numeric(14,2) NOT NULL DEFAULT 2000 CHECK(referral_reward >= 0), minimum_withdrawal numeric(14,2) NOT NULL DEFAULT 20000 CHECK(minimum_withdrawal > 0), withdrawal_fee numeric(14,2) NOT NULL DEFAULT 3000 CHECK(withdrawal_fee >= 0), welcome_bonus_amount numeric(14,2) NOT NULL DEFAULT 3000 CHECK(welcome_bonus_amount > 0), welcome_bonus_payout_enabled boolean NOT NULL DEFAULT false, welcome_bonus_budget_remaining numeric(14,2) NOT NULL DEFAULT 0 CHECK(welcome_bonus_budget_remaining >= 0), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.platform_financial_controls (id boolean PRIMARY KEY DEFAULT true CHECK(id), earnings_enabled boolean NOT NULL DEFAULT true, withdrawals_enabled boolean NOT NULL DEFAULT true, require_verified_contacts boolean NOT NULL DEFAULT true, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.wallet_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, entry_type text NOT NULL CHECK(entry_type IN ('promotional_bonus','real_earnings','referral_bonus','withdrawable_balance','pending_withdrawal','platform_fee')), amount numeric(14,2) NOT NULL, currency text NOT NULL, reference text, direction text NOT NULL DEFAULT 'debit' CHECK(direction IN ('credit','debit')), metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.platform_revenue (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source text NOT NULL CHECK(source IN ('withdrawal_fee','advertising','other')), amount numeric(14,2) NOT NULL CHECK(amount >= 0), currency text NOT NULL, reference text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source,reference));
CREATE TABLE public.referrals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), referrer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, referred_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, referral_code text NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','qualified','rejected')), qualified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK(referrer_id <> referred_id));
CREATE TABLE public.platform_promotional_expenses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), expense_type text NOT NULL CHECK(expense_type = 'WELCOME_BONUS_PROMOTIONAL_EXPENSE'), amount numeric(14,2) NOT NULL CHECK(amount > 0), currency text NOT NULL, reference text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.welcome_bonus_payouts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, bank_account_id uuid NOT NULL REFERENCES public.bank_accounts(id), reference text NOT NULL UNIQUE, provider text NOT NULL, provider_reference text, recipient_reference text NOT NULL, amount numeric(14,2) NOT NULL CHECK(amount > 0), currency text NOT NULL CHECK(currency='NGN'), status text NOT NULL CHECK(status IN ('PENDING_VERIFICATION','ELIGIBLE','PAYOUT_QUEUED','PROCESSING','PAID','FAILED','EXPIRED','CANCELLED')), consented_at timestamptz, queued_at timestamptz, processing_at timestamptz, paid_at timestamptz, failed_at timestamptz, failure_reason text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ai_conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, title text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ai_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, conversation_id uuid REFERENCES public.ai_conversations(id) ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('user','assistant','system')), parts jsonb NOT NULL DEFAULT '[]'::jsonb, client_message_id text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ai_user_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, key text NOT NULL, value jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,key));
CREATE TABLE public.ai_creator_analytics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, video_id uuid REFERENCES public.videos(id) ON DELETE SET NULL, views integer NOT NULL DEFAULT 0, likes integer NOT NULL DEFAULT 0, comments integer NOT NULL DEFAULT 0, shares integer NOT NULL DEFAULT 0, watch_time integer NOT NULL DEFAULT 0, completion_rate numeric NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.external_videos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_platform text NOT NULL, original_content_id text NOT NULL, original_url text NOT NULL, creator_name text NOT NULL, creator_attribution text NOT NULL, thumbnail_url text, embed_url text, title text NOT NULL, description text, category text NOT NULL, published_at timestamptz, ingested_at timestamptz NOT NULL DEFAULT now(), authorization_type text NOT NULL, external_status text NOT NULL DEFAULT 'active', last_synced_at timestamptz, country_code text, language_code text, source_metadata jsonb NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_platform,original_content_id));
CREATE TABLE public.external_ingestion_config (id boolean PRIMARY KEY DEFAULT true CHECK(id), automatic_ingestion_enabled boolean NOT NULL DEFAULT false, user_upload_priority numeric(5,2) NOT NULL DEFAULT .70, max_external_feed_ratio numeric(5,2) NOT NULL DEFAULT .30, external_content_limit integer NOT NULL DEFAULT 20, ingestion_frequency_minutes integer NOT NULL DEFAULT 360, approved_categories text[] NOT NULL DEFAULT ARRAY['Funny','Music','Experience','Sports','Learning','Serious Topics'], supported_countries text[] NOT NULL DEFAULT ARRAY['NG'], enabled_providers text[] NOT NULL DEFAULT ARRAY[]::text[], updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.external_ingestion_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider text NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz, discovered_count integer NOT NULL DEFAULT 0, imported_count integer NOT NULL DEFAULT 0, unavailable_count integer NOT NULL DEFAULT 0, error_message text);
CREATE TABLE public.advertisers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, company_name text NOT NULL, contact_email text NOT NULL, country text, website text, is_approved boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id));
CREATE TABLE public.ad_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), advertiser_id uuid NOT NULL REFERENCES public.advertisers(id) ON DELETE CASCADE, name text NOT NULL, headline text, description text, media_path text, destination_url text, budget numeric NOT NULL DEFAULT 0, spent numeric NOT NULL DEFAULT 0, cost_per_view numeric NOT NULL DEFAULT .01, cost_per_click numeric NOT NULL DEFAULT .10, target_countries text[] NOT NULL DEFAULT '{}', target_categories public.video_category[] NOT NULL DEFAULT '{}', status public.campaign_status NOT NULL DEFAULT 'pending_review', starts_at timestamptz, ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ad_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid NOT NULL REFERENCES public.ad_campaigns(id) ON DELETE CASCADE, event_type public.ad_event_type NOT NULL, viewer_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, country text, device text, cost numeric NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX profiles_referral_code_idx ON public.profiles(referral_code);
CREATE UNIQUE INDEX profiles_email_normalized_idx ON public.profiles(email_normalized) WHERE email_normalized IS NOT NULL;
CREATE UNIQUE INDEX profiles_registration_phone_idx ON public.profiles(registration_phone) WHERE registration_phone IS NOT NULL;
CREATE INDEX videos_created_at_idx ON public.videos(created_at DESC); CREATE INDEX videos_user_id_idx ON public.videos(user_id); CREATE INDEX videos_category_idx ON public.videos(category);
CREATE INDEX video_views_video_created_idx ON public.video_views(video_id,created_at DESC); CREATE INDEX video_views_creator_created_idx ON public.video_views(creator_id,created_at DESC); CREATE INDEX video_views_viewer_created_idx ON public.video_views(viewer_id,created_at DESC);
CREATE UNIQUE INDEX earnings_external_reference_idx ON public.earnings(user_id,external_reference) WHERE external_reference IS NOT NULL;
CREATE UNIQUE INDEX wallet_ledger_idempotency_idx ON public.wallet_ledger(user_id,entry_type,reference) WHERE reference IS NOT NULL;
CREATE UNIQUE INDEX withdrawals_user_idempotency_idx ON public.withdrawals(user_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX verification_challenges_active_idx ON public.verification_challenges(user_id,channel,created_at DESC) WHERE consumed_at IS NULL;
CREATE INDEX referrals_referrer_status_idx ON public.referrals(referrer_id,status); CREATE INDEX welcome_bonus_payouts_status_idx ON public.welcome_bonus_payouts(status);
CREATE INDEX ai_conversations_user_created_idx ON public.ai_conversations(user_id,created_at); CREATE INDEX ai_messages_conversation_created_idx ON public.ai_messages(conversation_id,created_at); CREATE INDEX ai_creator_analytics_user_idx ON public.ai_creator_analytics(user_id,created_at);

INSERT INTO storage.buckets(id,name,public) VALUES('videos','videos',false),('thumbnails','thumbnails',false) ON CONFLICT(id) DO UPDATE SET public=false;
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
CREATE POLICY storage_media_read ON storage.objects FOR SELECT TO authenticated USING(bucket_id IN ('videos','thumbnails') AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY storage_media_upload ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id IN ('videos','thumbnails') AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY storage_media_update ON storage.objects FOR UPDATE TO authenticated USING(bucket_id IN ('videos','thumbnails') AND (storage.foldername(name))[1]=auth.uid()::text) WITH CHECK(bucket_id IN ('videos','thumbnails') AND (storage.foldername(name))[1]=auth.uid()::text);
CREATE POLICY storage_media_delete ON storage.objects FOR DELETE TO authenticated USING(bucket_id IN ('videos','thumbnails') AND (storage.foldername(name))[1]=auth.uid()::text);

INSERT INTO public.payout_config(id) VALUES(true); INSERT INTO public.platform_reward_config(id) VALUES(true); INSERT INTO public.platform_financial_controls(id) VALUES(true); INSERT INTO public.supported_countries(country_code,country_name,currency,locale,is_live) VALUES('NG','Nigeria','NGN','en-NG',true); INSERT INTO public.external_ingestion_config(id) VALUES(true);

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$ BEGIN NEW.updated_at=now(); RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE OR REPLACE FUNCTION public.handle_new_auth_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE email_value text:=lower(btrim(NEW.email)); BEGIN INSERT INTO public.profiles(id,display_name,username,email_normalized) VALUES(NEW.id,COALESCE(NEW.raw_user_meta_data->>'display_name',split_part(email_value,'@',1),'New creator'),split_part(COALESCE(email_value,NEW.id::text),'@',1)||'_'||substr(NEW.id::text,1,6),email_value) ON CONFLICT(id) DO NOTHING; INSERT INTO public.wallets(user_id) VALUES(NEW.id) ON CONFLICT(user_id) DO NOTHING; RETURN NEW; END $$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();
CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); CREATE TRIGGER videos_set_updated_at BEFORE UPDATE ON public.videos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); CREATE TRIGGER wallets_set_updated_at BEFORE UPDATE ON public.wallets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at(); CREATE TRIGGER withdrawals_set_updated_at BEFORE UPDATE ON public.withdrawals FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
INSERT INTO public.profiles(id,display_name,username,email_normalized) SELECT id,COALESCE(raw_user_meta_data->>'display_name',split_part(email,'@',1),'New creator'),split_part(COALESCE(email,id::text),'@',1)||'_'||substr(id::text,1,6),lower(btrim(email)) FROM auth.users ON CONFLICT(id) DO NOTHING;
INSERT INTO public.wallets(user_id) SELECT id FROM public.profiles ON CONFLICT(user_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.normalize_email(p_email text) RETURNS text LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT lower(btrim(p_email)) $$;
CREATE OR REPLACE FUNCTION public.normalize_registration_phone(p_phone text) RETURNS text LANGUAGE plpgsql IMMUTABLE STRICT AS $$ DECLARE value text:=regexp_replace(btrim(p_phone),'[\s().-]','','g'); BEGIN IF value !~ '^\+[1-9][0-9]{7,14}$' THEN RAISE EXCEPTION 'Use an international phone number'; END IF; RETURN value; END $$;
CREATE TABLE public.blocked_disposable_email_domains(domain text PRIMARY KEY); CREATE TABLE public.blocked_phone_prefixes(prefix text PRIMARY KEY);
INSERT INTO public.blocked_disposable_email_domains(domain) VALUES('10minutemail.com'),('guerrillamail.com'),('mailinator.com'),('tempmail.com'),('temp-mail.org'),('yopmail.com');
CREATE OR REPLACE FUNCTION public.is_disposable_email(p_email text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT split_part(public.normalize_email(p_email),'@',2) IN (SELECT domain FROM public.blocked_disposable_email_domains) $$;
CREATE OR REPLACE FUNCTION public.is_blocked_phone(p_phone text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.blocked_phone_prefixes WHERE public.normalize_registration_phone(p_phone) LIKE prefix||'%') $$;
CREATE OR REPLACE FUNCTION public.start_verification_challenge(p_channel text,p_target text,p_code_hash text,p_expires_at timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE challenge_id uuid; target_value text:=btrim(p_target); BEGIN IF auth.uid() IS NULL OR p_channel NOT IN('phone','email') THEN RAISE EXCEPTION 'Invalid verification request'; END IF; IF p_channel='phone' THEN target_value:=public.normalize_registration_phone(target_value); IF public.is_blocked_phone(target_value) THEN RAISE EXCEPTION 'This phone number type is not accepted'; END IF; ELSE target_value:=public.normalize_email(target_value); IF public.is_disposable_email(target_value) THEN RAISE EXCEPTION 'Disposable email addresses are not accepted'; END IF; END IF; UPDATE public.verification_challenges SET consumed_at=now() WHERE user_id=auth.uid() AND channel=p_channel AND consumed_at IS NULL; INSERT INTO public.account_verifications(user_id) VALUES(auth.uid()) ON CONFLICT DO NOTHING; INSERT INTO public.verification_challenges(user_id,channel,target,code_hash,expires_at) VALUES(auth.uid(),p_channel,target_value,p_code_hash,p_expires_at) RETURNING id INTO challenge_id; RETURN challenge_id; END $$;

CREATE OR REPLACE FUNCTION public.video_likes_count_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='INSERT' THEN UPDATE public.videos SET likes_count=likes_count+1 WHERE id=NEW.video_id; ELSE UPDATE public.videos SET likes_count=GREATEST(likes_count-1,0) WHERE id=OLD.video_id; END IF; RETURN COALESCE(NEW,OLD); END $$;
CREATE OR REPLACE FUNCTION public.video_comments_count_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='INSERT' THEN UPDATE public.videos SET comments_count=comments_count+1 WHERE id=NEW.video_id; ELSE UPDATE public.videos SET comments_count=GREATEST(comments_count-1,0) WHERE id=OLD.video_id; END IF; RETURN COALESCE(NEW,OLD); END $$;
CREATE TRIGGER video_likes_after_insert AFTER INSERT ON public.video_likes FOR EACH ROW EXECUTE FUNCTION public.video_likes_count_change(); CREATE TRIGGER video_likes_after_delete AFTER DELETE ON public.video_likes FOR EACH ROW EXECUTE FUNCTION public.video_likes_count_change(); CREATE TRIGGER video_comments_after_insert AFTER INSERT ON public.video_comments FOR EACH ROW EXECUTE FUNCTION public.video_comments_count_change(); CREATE TRIGGER video_comments_after_delete AFTER DELETE ON public.video_comments FOR EACH ROW EXECUTE FUNCTION public.video_comments_count_change();

CREATE OR REPLACE FUNCTION public.apply_earning_to_wallet() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE ledger_id uuid; wallet_currency text; reference_value text:=COALESCE(NEW.external_reference,'earning:'||NEW.id::text); BEGIN IF NEW.amount<=0 THEN RETURN NEW; END IF; IF NOT COALESCE((SELECT earnings_enabled FROM public.platform_financial_controls WHERE id),true) THEN RAISE EXCEPTION 'Creator earnings are temporarily paused'; END IF; SELECT currency INTO wallet_currency FROM public.wallets WHERE user_id=NEW.user_id FOR UPDATE; INSERT INTO public.wallet_ledger(user_id,entry_type,amount,currency,reference,direction,metadata) VALUES(NEW.user_id,'real_earnings',NEW.amount,COALESCE(wallet_currency,'NGN'),reference_value,'credit',jsonb_build_object('source',NEW.source,'video_id',NEW.video_id)) ON CONFLICT(user_id,entry_type,reference) DO NOTHING RETURNING id INTO ledger_id; IF ledger_id IS NULL THEN RETURN NEW; END IF; INSERT INTO public.wallets(user_id,available_balance,real_earnings_balance,lifetime_earned,currency) VALUES(NEW.user_id,NEW.amount,NEW.amount,NEW.amount,COALESCE(wallet_currency,'NGN')) ON CONFLICT(user_id) DO UPDATE SET available_balance=public.wallets.available_balance+NEW.amount,real_earnings_balance=public.wallets.real_earnings_balance+NEW.amount,lifetime_earned=public.wallets.lifetime_earned+NEW.amount,updated_at=now(); RETURN NEW; END $$;
CREATE TRIGGER earnings_apply_to_wallet AFTER INSERT ON public.earnings FOR EACH ROW EXECUTE FUNCTION public.apply_earning_to_wallet();
CREATE OR REPLACE FUNCTION public.credit_earning(_user_id uuid,_amount numeric,_source public.earning_source,_note text DEFAULT NULL,_video_id uuid DEFAULT NULL,_reference text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE earning_id uuid; BEGIN IF _user_id IS NULL OR _amount IS NULL OR _amount<=0 OR NULLIF(btrim(_reference),'') IS NULL THEN RETURN NULL; END IF; INSERT INTO public.earnings(user_id,amount,source,note,video_id,external_reference) VALUES(_user_id,_amount,_source,_note,_video_id,btrim(_reference)) ON CONFLICT(user_id,external_reference) DO NOTHING RETURNING id INTO earning_id; IF earning_id IS NULL THEN SELECT id INTO earning_id FROM public.earnings WHERE user_id=_user_id AND external_reference=btrim(_reference); END IF; RETURN earning_id; END $$;
CREATE OR REPLACE FUNCTION public.grant_reward(_user_id uuid,_kind public.reward_kind,_reference text,_amount numeric,_note text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE claim_id uuid; BEGIN IF _amount IS NULL OR _amount<=0 THEN RETURN jsonb_build_object('granted',false,'reason','invalid'); END IF; INSERT INTO public.reward_claims(user_id,kind,reference,amount) VALUES(_user_id,_kind,btrim(_reference),_amount) ON CONFLICT(user_id,kind,reference) DO NOTHING RETURNING id INTO claim_id; IF claim_id IS NULL THEN RETURN jsonb_build_object('granted',false,'reason','already_claimed'); END IF; PERFORM public.credit_earning(_user_id,_amount,CASE WHEN _kind='referral' THEN 'referral'::public.earning_source ELSE 'bonus'::public.earning_source END,_note,NULL,'reward:'||_kind::text||':'||btrim(_reference)); RETURN jsonb_build_object('granted',true,'amount',_amount); END $$;
CREATE OR REPLACE FUNCTION public.claim_daily_login() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); cfg public.payout_config; BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF; SELECT * INTO cfg FROM public.payout_config WHERE id; RETURN public.grant_reward(uid,'daily_login',to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD'),cfg.daily_login_reward,'Daily login reward'); END $$;

CREATE OR REPLACE FUNCTION public.toggle_like(p_video_id uuid) RETURNS TABLE(action text,likes_count bigint) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); existing uuid; BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF; PERFORM 1 FROM public.videos WHERE id=p_video_id FOR UPDATE; SELECT id INTO existing FROM public.video_likes WHERE video_id=p_video_id AND user_id=uid; IF existing IS NULL THEN INSERT INTO public.video_likes(video_id,user_id) VALUES(p_video_id,uid); action:='liked'; ELSE DELETE FROM public.video_likes WHERE id=existing; action:='unliked'; END IF; SELECT COALESCE(likes_count,0) INTO likes_count FROM public.videos WHERE id=p_video_id; RETURN NEXT; END $$;
CREATE OR REPLACE FUNCTION public.record_video_view(_video_id uuid,_watch_seconds integer,_percent_watched numeric,_device text DEFAULT NULL,_country text DEFAULT NULL,_session_key text DEFAULT NULL,_ip_hash text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE cfg public.payout_config; viewer uuid:=auth.uid(); creator uuid; duration integer; view_id uuid; views integer; amount numeric:=0; duplicate boolean; BEGIN SELECT user_id,duration_seconds INTO creator,duration FROM public.videos WHERE id=_video_id; IF creator IS NULL THEN RAISE EXCEPTION 'Video not found'; END IF; SELECT * INTO cfg FROM public.payout_config WHERE id; PERFORM pg_advisory_xact_lock(hashtext(_video_id::text||':'||COALESCE(viewer::text,_ip_hash,_session_key,'anon'))); SELECT EXISTS(SELECT 1 FROM public.video_views WHERE video_id=_video_id AND is_valid AND created_at>now()-make_interval(mins=>cfg.dedup_window_minutes) AND ((viewer IS NOT NULL AND viewer_id=viewer) OR (viewer IS NULL AND _ip_hash IS NOT NULL AND ip_hash=_ip_hash))) INTO duplicate; IF NOT duplicate AND (COALESCE(_watch_seconds,0)>0 OR COALESCE(_percent_watched,0)>0) AND (duration IS NULL OR _watch_seconds<=duration*2) THEN amount:=LEAST(cfg.rate_per_view,cfg.daily_creator_limit-COALESCE((SELECT sum(earned_amount) FROM public.video_views WHERE creator_id=creator AND created_at>=date_trunc('day',now())),0),cfg.per_viewer_daily_limit-COALESCE((SELECT sum(earned_amount) FROM public.video_views WHERE viewer_id=viewer AND created_at>=date_trunc('day',now())),0)); IF amount<0 THEN amount:=0; END IF; END IF; INSERT INTO public.video_views(video_id,creator_id,viewer_id,session_key,watch_seconds,percent_watched,device,ip_hash,country,is_valid,earned_amount) VALUES(_video_id,creator,viewer,_session_key,GREATEST(COALESCE(_watch_seconds,0),0),LEAST(GREATEST(COALESCE(_percent_watched,0),0),100),_device,_ip_hash,_country,NOT duplicate,amount) RETURNING id INTO view_id; IF NOT duplicate THEN UPDATE public.videos SET views_count=views_count+1 WHERE id=_video_id RETURNING views_count INTO views; IF amount>0 THEN PERFORM public.credit_earning(creator,amount,'views','Verified view earnings',_video_id,'view:'||view_id::text); END IF; IF views IN(1000,10000,100000,1000000) THEN PERFORM public.grant_reward(creator,'milestone',_video_id::text||':'||views::text,cfg.milestone_reward,'Views milestone'); END IF; END IF; RETURN jsonb_build_object('valid',NOT duplicate,'earned',amount); END $$;

CREATE OR REPLACE FUNCTION public.request_withdrawal(_amount numeric,_method text,_destination text) RETURNS public.withdrawals LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); available numeric; fee numeric; minimum numeric; currency_code text; key text; result public.withdrawals; BEGIN IF uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF; SELECT minimum_withdrawal,withdrawal_fee INTO minimum,fee FROM public.platform_reward_config WHERE id AND country_code='NG'; IF _amount IS NULL OR _amount<COALESCE(minimum,20000) THEN RAISE EXCEPTION 'Minimum withdrawal is %',COALESCE(minimum,20000); END IF; key:=encode(digest(uid::text||':'||_amount::text||':'||btrim(_method)||':'||btrim(_destination),'sha256'),'hex'); SELECT * INTO result FROM public.withdrawals WHERE user_id=uid AND idempotency_key=key; IF result.id IS NOT NULL THEN RETURN result; END IF; SELECT available_balance,currency INTO available,currency_code FROM public.wallets WHERE user_id=uid FOR UPDATE; IF available IS NULL OR available<_amount THEN RAISE EXCEPTION 'Insufficient eligible real earnings'; END IF; INSERT INTO public.withdrawals(user_id,amount,method,destination,platform_fee,payout_amount,idempotency_key) VALUES(uid,_amount,btrim(_method),btrim(_destination),LEAST(COALESCE(fee,0),_amount),_amount-LEAST(COALESCE(fee,0),_amount),key) ON CONFLICT(user_id,idempotency_key) DO NOTHING RETURNING * INTO result; IF result.id IS NULL THEN SELECT * INTO result FROM public.withdrawals WHERE user_id=uid AND idempotency_key=key; RETURN result; END IF; UPDATE public.wallets SET available_balance=available_balance-_amount,pending_balance=pending_balance+_amount,withdrawal_reserved_balance=withdrawal_reserved_balance+_amount WHERE user_id=uid; INSERT INTO public.wallet_ledger(user_id,entry_type,amount,currency,reference,direction) VALUES(uid,'pending_withdrawal',_amount,COALESCE(currency_code,'NGN'),'withdrawal:'||result.id::text,'debit'),(uid,'platform_fee',LEAST(COALESCE(fee,0),_amount),COALESCE(currency_code,'NGN'),'withdrawal-fee:'||result.id::text,'debit') ON CONFLICT DO NOTHING; INSERT INTO public.platform_revenue(source,amount,currency,reference) VALUES('withdrawal_fee',LEAST(COALESCE(fee,0),_amount),COALESCE(currency_code,'NGN'),result.id::text) ON CONFLICT DO NOTHING; RETURN result; END $$;

CREATE OR REPLACE FUNCTION public.create_pending_verification_bonus() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE reward numeric; currency_code text; BEGIN SELECT signup_bonus INTO reward FROM public.platform_reward_config WHERE id AND country_code='NG'; SELECT currency INTO currency_code FROM public.wallets WHERE user_id=NEW.id; IF reward>0 THEN INSERT INTO public.verification_bonus_claims(user_id,amount,currency,status,expires_at) VALUES(NEW.id,reward,COALESCE(currency_code,'NGN'),'PENDING_VERIFICATION_BONUS',now()+interval '30 days') ON CONFLICT(user_id) DO NOTHING; END IF; RETURN NEW; END $$;
CREATE TRIGGER profiles_pending_verification_bonus AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.create_pending_verification_bonus();
CREATE OR REPLACE FUNCTION public.complete_verification(p_channel text,p_code_hash text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE challenge public.verification_challenges; fully_verified boolean; BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF; SELECT * INTO challenge FROM public.verification_challenges WHERE user_id=auth.uid() AND channel=p_channel AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1 FOR UPDATE; IF challenge.id IS NULL OR challenge.expires_at<=now() OR challenge.attempts>=5 THEN RAISE EXCEPTION 'Code expired or unavailable'; END IF; UPDATE public.verification_challenges SET attempts=attempts+1 WHERE id=challenge.id; IF challenge.code_hash<>p_code_hash THEN RAISE EXCEPTION 'Invalid verification code'; END IF; UPDATE public.verification_challenges SET consumed_at=now() WHERE id=challenge.id; INSERT INTO public.account_verifications(user_id) VALUES(auth.uid()) ON CONFLICT DO NOTHING; IF p_channel='phone' THEN UPDATE public.account_verifications SET phone_verified_at=now(),updated_at=now() WHERE user_id=auth.uid(); ELSIF p_channel='email' THEN UPDATE public.account_verifications SET email_verified_at=now(),updated_at=now() WHERE user_id=auth.uid(); ELSE RAISE EXCEPTION 'Invalid verification channel'; END IF; SELECT phone_verified_at IS NOT NULL AND email_verified_at IS NOT NULL INTO fully_verified FROM public.account_verifications WHERE user_id=auth.uid(); IF fully_verified THEN UPDATE public.verification_bonus_claims SET amount=cfg.welcome_bonus_amount,currency='NGN' FROM public.platform_reward_config cfg WHERE user_id=auth.uid() AND status='PENDING_VERIFICATION_BONUS' AND cfg.id AND cfg.country_code='NG'; END IF; RETURN true; END $$;
CREATE OR REPLACE FUNCTION public.claim_welcome_bonus_payout(p_reference text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Forbidden'; END IF; UPDATE public.welcome_bonus_payouts SET status='PROCESSING',processing_at=COALESCE(processing_at,now()),updated_at=now() WHERE reference=p_reference AND status='PAYOUT_QUEUED'; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.mark_welcome_bonus_processing(p_reference text,p_provider_reference text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Forbidden'; END IF; UPDATE public.welcome_bonus_payouts SET provider_reference=p_provider_reference,updated_at=now() WHERE reference=p_reference AND status='PROCESSING' AND provider_reference IS NULL; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.confirm_welcome_bonus_paid(p_reference text,p_provider_reference text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Forbidden'; END IF; UPDATE public.welcome_bonus_payouts SET status='PAID',provider_reference=COALESCE(p_provider_reference,provider_reference),paid_at=COALESCE(paid_at,now()),updated_at=now() WHERE reference=p_reference AND provider='paystack' AND status='PROCESSING'; RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.fail_welcome_bonus_payout(p_reference text,p_reason text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Forbidden'; END IF; UPDATE public.welcome_bonus_payouts SET status='FAILED',failure_reason=left(NULLIF(btrim(p_reason),''),500),failed_at=COALESCE(failed_at,now()),updated_at=now() WHERE reference=p_reference AND status IN('PAYOUT_QUEUED','PROCESSING'); RETURN FOUND; END $$;
CREATE OR REPLACE FUNCTION public.retry_welcome_bonus_payout(p_reference text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF auth.role()<>'service_role' THEN RAISE EXCEPTION 'Forbidden'; END IF; UPDATE public.welcome_bonus_payouts SET status='PAYOUT_QUEUED',failure_reason=NULL,failed_at=NULL,queued_at=now(),updated_at=now() WHERE reference=p_reference AND status='FAILED' AND provider_reference IS NULL; RETURN FOUND; END $$;

CREATE OR REPLACE FUNCTION public.register_referral(p_referral_code text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE uid uuid:=auth.uid(); referrer uuid; id_value uuid; BEGIN SELECT id INTO referrer FROM public.profiles WHERE referral_code=upper(btrim(p_referral_code)) AND id<>uid; IF referrer IS NULL THEN RAISE EXCEPTION 'Referral code not found'; END IF; INSERT INTO public.referrals(referrer_id,referred_id,referral_code) VALUES(referrer,uid,upper(btrim(p_referral_code))) ON CONFLICT(referred_id) DO NOTHING RETURNING id INTO id_value; RETURN jsonb_build_object('registered',id_value IS NOT NULL); END $$;
CREATE OR REPLACE FUNCTION public.qualify_referral(p_referred_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE r public.referrals; reward numeric; target integer; count_value integer; BEGIN IF NOT public.has_role(auth.uid(),'admin') THEN RAISE EXCEPTION 'Forbidden'; END IF; SELECT * INTO r FROM public.referrals WHERE referred_id=p_referred_id FOR UPDATE; IF r.id IS NULL OR r.status<>'pending' THEN RETURN jsonb_build_object('qualified',false); END IF; IF NOT EXISTS(SELECT 1 FROM public.account_verifications WHERE user_id=r.referred_id AND phone_verified_at IS NOT NULL AND email_verified_at IS NOT NULL) THEN RAISE EXCEPTION 'Verification required'; END IF; SELECT referral_reward,referral_target INTO reward,target FROM public.platform_reward_config WHERE id AND country_code='NG'; SELECT count(*) INTO count_value FROM public.referrals WHERE referrer_id=r.referrer_id AND status='qualified'; UPDATE public.referrals SET status='qualified',qualified_at=now() WHERE id=r.id; IF count_value+1>=target THEN PERFORM public.grant_reward(r.referrer_id,'referral','referral-target:'||target::text,reward,'Referral reward'); END IF; RETURN jsonb_build_object('qualified',true,'reward_unlocked',count_value+1>=target); END $$;

-- Final welcome queue definition: entitlement remains pending until provider success.
CREATE OR REPLACE FUNCTION public.queue_welcome_bonus_payout(p_bank_account_id uuid,p_consent boolean) RETURNS public.welcome_bonus_payouts LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE uid uuid:=auth.uid(); claim public.verification_bonus_claims; bank public.bank_accounts; cfg public.platform_reward_config; result public.welcome_bonus_payouts; reference text;
BEGIN
  IF uid IS NULL OR NOT p_consent THEN RAISE EXCEPTION 'Authentication and consent required'; END IF;
  SELECT * INTO cfg FROM public.platform_reward_config WHERE id AND country_code='NG' FOR UPDATE;
  SELECT * INTO claim FROM public.verification_bonus_claims WHERE user_id=uid FOR UPDATE;
  IF claim.id IS NULL OR claim.status<>'PENDING_VERIFICATION_BONUS' OR claim.expires_at<=now() OR cfg.welcome_bonus_payout_enabled IS NOT TRUE OR cfg.welcome_bonus_budget_remaining<cfg.welcome_bonus_amount THEN RAISE EXCEPTION 'Welcome bonus is not eligible'; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.account_verifications WHERE user_id=uid AND phone_verified_at IS NOT NULL AND email_verified_at IS NOT NULL) THEN RAISE EXCEPTION 'Phone and email verification are required'; END IF;
  SELECT * INTO bank FROM public.bank_accounts WHERE id=p_bank_account_id AND creator_id=uid FOR UPDATE;
  IF bank.id IS NULL OR bank.provider<>'paystack' OR bank.verified IS NOT TRUE OR bank.external_id IS NULL THEN RAISE EXCEPTION 'A verified Paystack bank account is required'; END IF;
  reference:='KCEARN-WELCOME-'||upper(replace(gen_random_uuid()::text,'-',''));
  INSERT INTO public.welcome_bonus_payouts(user_id,bank_account_id,reference,provider,recipient_reference,amount,currency,status,consented_at,queued_at) VALUES(uid,bank.id,reference,bank.provider,bank.external_id,cfg.welcome_bonus_amount,'NGN','PAYOUT_QUEUED',now(),now()) ON CONFLICT(user_id) DO NOTHING RETURNING * INTO result;
  IF result.id IS NULL THEN SELECT * INTO result FROM public.welcome_bonus_payouts WHERE user_id=uid; RETURN result; END IF;
  UPDATE public.platform_reward_config SET welcome_bonus_budget_remaining=welcome_bonus_budget_remaining-cfg.welcome_bonus_amount WHERE id;
  INSERT INTO public.platform_promotional_expenses(expense_type,amount,currency,reference) VALUES('WELCOME_BONUS_PROMOTIONAL_EXPENSE',result.amount,result.currency,result.reference);
  RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.push_notification(_user_id uuid,_kind public.notification_kind,_title text,_body text DEFAULT NULL,_metadata jsonb DEFAULT '{}') RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE id_value uuid; BEGIN INSERT INTO public.notifications(user_id,kind,title,body,metadata) VALUES(_user_id,_kind,_title,_body,COALESCE(_metadata,'{}')) RETURNING id INTO id_value; RETURN id_value; END $$;
CREATE OR REPLACE FUNCTION public.owns_advertiser(_advertiser_id uuid,_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.advertisers WHERE id=_advertiser_id AND owner_id=_user_id) $$;
CREATE OR REPLACE FUNCTION public.record_ad_event(_campaign_id uuid,_event_type public.ad_event_type,_country text DEFAULT NULL,_device text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.ad_events(campaign_id,event_type,viewer_id,country,device) VALUES(_campaign_id,_event_type,auth.uid(),_country,_device); RETURN jsonb_build_object('recorded',true); END $$;
CREATE OR REPLACE FUNCTION public.creator_analytics(_user_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT jsonb_build_object('videos',count(*),'views',COALESCE(sum(views_count),0),'likes',COALESCE(sum(likes_count),0),'comments',COALESCE(sum(comments_count),0)) FROM public.videos WHERE user_id=COALESCE(_user_id,auth.uid()) $$;
CREATE OR REPLACE FUNCTION public.admin_platform_stats() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT public.has_role(auth.uid(),'admin') THEN RAISE EXCEPTION 'Forbidden'; END IF; RETURN jsonb_build_object('users',(SELECT count(*) FROM auth.users),'videos',(SELECT count(*) FROM public.videos),'withdrawals',(SELECT count(*) FROM public.withdrawals)); END $$;
CREATE OR REPLACE FUNCTION public.admin_set_campaign_status(_campaign_id uuid,_status public.campaign_status) RETURNS public.ad_campaigns LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE result public.ad_campaigns; BEGIN IF NOT public.has_role(auth.uid(),'admin') THEN RAISE EXCEPTION 'Forbidden'; END IF; UPDATE public.ad_campaigns SET status=_status,updated_at=now() WHERE id=_campaign_id RETURNING * INTO result; RETURN result; END $$;
CREATE OR REPLACE FUNCTION public.admin_update_withdrawal(_withdrawal_id uuid,_status public.withdrawal_status,_note text DEFAULT NULL) RETURNS public.withdrawals LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE result public.withdrawals; BEGIN IF NOT public.has_role(auth.uid(),'admin') THEN RAISE EXCEPTION 'Forbidden'; END IF; SELECT * INTO result FROM public.withdrawals WHERE id=_withdrawal_id FOR UPDATE; IF result.id IS NULL THEN RAISE EXCEPTION 'Withdrawal not found'; END IF; UPDATE public.withdrawals SET status=_status,note=_note,updated_at=now() WHERE id=_withdrawal_id RETURNING * INTO result; RETURN result; END $$;

-- RLS is enabled after all tables exist; direct financial writes are intentionally absent.
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['profiles','videos','wallets','earnings','withdrawals','user_roles','payout_config','video_views','reward_claims','video_likes','follows','video_comments','notifications','bank_accounts','account_verifications','verification_challenges','verification_bonus_claims','supported_countries','platform_reward_config','platform_financial_controls','wallet_ledger','platform_revenue','referrals','platform_promotional_expenses','welcome_bonus_payouts','ai_conversations','ai_messages','ai_user_preferences','ai_creator_analytics','external_videos','external_ingestion_config','external_ingestion_runs','advertisers','ad_campaigns','ad_events'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); END LOOP; END $$;
CREATE POLICY profiles_public_read ON public.profiles FOR SELECT USING(true); CREATE POLICY profiles_self_update ON public.profiles FOR UPDATE TO authenticated USING(auth.uid()=id) WITH CHECK(auth.uid()=id);
CREATE POLICY videos_public_published ON public.videos FOR SELECT USING(status='published'); CREATE POLICY videos_owner_write ON public.videos FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id);
CREATE POLICY wallets_owner_read ON public.wallets FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY earnings_owner_read ON public.earnings FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY withdrawals_owner_read ON public.withdrawals FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY reward_claims_owner_read ON public.reward_claims FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY wallet_ledger_owner_read ON public.wallet_ledger FOR SELECT TO authenticated USING(auth.uid()=user_id);
CREATE POLICY likes_public_read ON public.video_likes FOR SELECT USING(true); CREATE POLICY likes_owner_insert ON public.video_likes FOR INSERT TO authenticated WITH CHECK(auth.uid()=user_id); CREATE POLICY likes_owner_delete ON public.video_likes FOR DELETE TO authenticated USING(auth.uid()=user_id);
CREATE POLICY follows_public_read ON public.follows FOR SELECT USING(true); CREATE POLICY follows_owner_insert ON public.follows FOR INSERT TO authenticated WITH CHECK(auth.uid()=follower_id); CREATE POLICY follows_owner_delete ON public.follows FOR DELETE TO authenticated USING(auth.uid()=follower_id);
CREATE POLICY comments_public_read ON public.video_comments FOR SELECT USING(true); CREATE POLICY comments_owner_insert ON public.video_comments FOR INSERT TO authenticated WITH CHECK(auth.uid()=user_id); CREATE POLICY comments_owner_update ON public.video_comments FOR UPDATE TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY comments_owner_delete ON public.video_comments FOR DELETE TO authenticated USING(auth.uid()=user_id);
CREATE POLICY notifications_owner_read ON public.notifications FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY verification_owner_read ON public.account_verifications FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY verification_claim_owner_read ON public.verification_bonus_claims FOR SELECT TO authenticated USING(auth.uid()=user_id); CREATE POLICY supported_countries_read ON public.supported_countries FOR SELECT USING(is_live); CREATE POLICY reward_config_read ON public.platform_reward_config FOR SELECT USING(true); CREATE POLICY payout_config_read ON public.payout_config FOR SELECT USING(true); CREATE POLICY referral_owner_read ON public.referrals FOR SELECT TO authenticated USING(auth.uid()=referrer_id OR auth.uid()=referred_id); CREATE POLICY ai_conversation_owner ON public.ai_conversations FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY ai_message_owner ON public.ai_messages FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY ai_preferences_owner ON public.ai_user_preferences FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY ai_analytics_owner ON public.ai_creator_analytics FOR ALL TO authenticated USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY external_videos_active_read ON public.external_videos FOR SELECT USING(external_status='active'); CREATE POLICY advertiser_owner ON public.advertisers FOR ALL TO authenticated USING(auth.uid()=owner_id) WITH CHECK(auth.uid()=owner_id); CREATE POLICY campaign_owner ON public.ad_campaigns FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.advertisers a WHERE a.id=advertiser_id AND a.owner_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.advertisers a WHERE a.id=advertiser_id AND a.owner_id=auth.uid()));
GRANT SELECT ON public.profiles,public.videos,public.video_likes,public.follows,public.video_comments,public.external_videos,public.supported_countries,public.platform_reward_config,public.payout_config TO anon,authenticated;
GRANT SELECT,UPDATE ON public.profiles TO authenticated; GRANT SELECT,INSERT,UPDATE,DELETE ON public.videos TO authenticated; GRANT SELECT ON public.wallets,public.earnings,public.withdrawals,public.reward_claims,public.wallet_ledger,public.referrals,public.notifications,public.video_views,public.ai_conversations,public.ai_messages,public.ai_user_preferences,public.ai_creator_analytics,public.welcome_bonus_payouts TO authenticated;
GRANT EXECUTE ON FUNCTION public.toggle_like(uuid),public.record_video_view(uuid,integer,numeric,text,text,text,text),public.claim_daily_login(),public.request_withdrawal(numeric,text,text),public.register_referral(text),public.qualify_referral(uuid),public.complete_verification(text,text),public.queue_welcome_bonus_payout(uuid,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.start_verification_challenge(text,text,text,timestamptz) TO authenticated;
REVOKE ALL ON FUNCTION public.apply_earning_to_wallet(),public.credit_earning(uuid,numeric,public.earning_source,text,uuid,text),public.grant_reward(uuid,public.reward_kind,text,numeric,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.claim_welcome_bonus_payout(text),public.mark_welcome_bonus_processing(text,text),public.confirm_welcome_bonus_paid(text,text),public.fail_welcome_bonus_payout(text,text),public.retry_welcome_bonus_payout(text) TO service_role;

COMMIT;
