/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiVideosTriggerProcessRouteImport } from './routes/api/videos/trigger-process'
import { Route as ApiPublicViewContextRouteImport } from './routes/api/public/view-context'
import { Route as ApiAiToolsRouteImport } from './routes/api/ai/tools'
import { Route as ApiAiPreferencesRouteImport } from './routes/api/ai/preferences'
import { Route as ApiAiAnalyticsRouteImport } from './routes/api/ai/analytics'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosTriggerProcessRoute = ApiVideosTriggerProcessRouteImport.update({
  id: '/api/videos/trigger-process',
  path: '/api/videos/trigger-process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicViewContextRoute = ApiPublicViewContextRouteImport.update({
  id: '/api/public/view-context',
  path: '/api/public/view-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiToolsRoute = ApiAiToolsRouteImport.update({
  id: '/api/ai/tools',
  path: '/api/ai/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPreferencesRoute = ApiAiPreferencesRouteImport.update({
  id: '/api/ai/preferences',
  path: '/api/ai/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyticsRoute = ApiAiAnalyticsRouteImport.update({
  id: '/api/ai/analytics',
  path: '/api/ai/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ai/analytics': typeof ApiAiAnalyticsRoute
  '/api/ai/preferences': typeof ApiAiPreferencesRoute
  '/api/ai/tools': typeof ApiAiToolsRoute
  '/api/public/view-context': typeof ApiPublicViewContextRoute
  '/api/videos/trigger-process': typeof ApiVideosTriggerProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ai/analytics': typeof ApiAiAnalyticsRoute
  '/api/ai/preferences': typeof ApiAiPreferencesRoute
  '/api/ai/tools': typeof ApiAiToolsRoute
  '/api/public/view-context': typeof ApiPublicViewContextRoute
  '/api/videos/trigger-process': typeof ApiVideosTriggerProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/api/chat': typeof ApiChatRoute
  '/api/ai/analytics': typeof ApiAiAnalyticsRoute
  '/api/ai/preferences': typeof ApiAiPreferencesRoute
  '/api/ai/tools': typeof ApiAiToolsRoute
  '/api/public/view-context': typeof ApiPublicViewContextRoute
  '/api/videos/trigger-process': typeof ApiVideosTriggerProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/upload'
    | '/api/chat'
    | '/api/ai/analytics'
    | '/api/ai/preferences'
    | '/api/ai/tools'
    | '/api/public/view-context'
    | '/api/videos/trigger-process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/upload'
    | '/api/chat'
    | '/api/ai/analytics'
    | '/api/ai/preferences'
    | '/api/ai/tools'
    | '/api/public/view-context'
    | '/api/videos/trigger-process'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/profile'
    | '/upload'
    | '/api/chat'
    | '/api/ai/analytics'
    | '/api/ai/preferences'
    | '/api/ai/tools'
    | '/api/public/view-context'
    | '/api/videos/trigger-process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  UploadRoute: typeof UploadRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAiAnalyticsRoute: typeof ApiAiAnalyticsRoute
  ApiAiPreferencesRoute: typeof ApiAiPreferencesRoute
  ApiAiToolsRoute: typeof ApiAiToolsRoute
  ApiPublicViewContextRoute: typeof ApiPublicViewContextRoute
  ApiVideosTriggerProcessRoute: typeof ApiVideosTriggerProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/trigger-process': {
      id: '/api/videos/trigger-process'
      path: '/api/videos/trigger-process'
      fullPath: '/api/videos/trigger-process'
      preLoaderRoute: typeof ApiVideosTriggerProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/view-context': {
      id: '/api/public/view-context'
      path: '/api/public/view-context'
      fullPath: '/api/public/view-context'
      preLoaderRoute: typeof ApiPublicViewContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/tools': {
      id: '/api/ai/tools'
      path: '/api/ai/tools'
      fullPath: '/api/ai/tools'
      preLoaderRoute: typeof ApiAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/preferences': {
      id: '/api/ai/preferences'
      path: '/api/ai/preferences'
      fullPath: '/api/ai/preferences'
      preLoaderRoute: typeof ApiAiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analytics': {
      id: '/api/ai/analytics'
      path: '/api/ai/analytics'
      fullPath: '/api/ai/analytics'
      preLoaderRoute: typeof ApiAiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  UploadRoute: UploadRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAiAnalyticsRoute: ApiAiAnalyticsRoute,
  ApiAiPreferencesRoute: ApiAiPreferencesRoute,
  ApiAiToolsRoute: ApiAiToolsRoute,
  ApiPublicViewContextRoute: ApiPublicViewContextRoute,
  ApiVideosTriggerProcessRoute: ApiVideosTriggerProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
